version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/wrapper"
    schedule:
      interval: "monthly"
    versioning-strategy: increase
    commit-message:
      prefix: "[Dependency Update]"
    groups:
      dependencies:
        patterns:
          - "*"
